# apps/crossplane/compositions/base/s3-bucket-composition-secure.yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3bucket-secure
  labels:
    security: enabled
spec:
  compositeTypeRef:
    apiVersion: s3.aws.engie.org/v1alpha1
    kind: XBucket
  mode: Pipeline
  pipeline:
    - step: s3bucket-and-policy
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          # Ressource 1: Le Bucket S3
          - name: s3bucket
            base:
              apiVersion: s3.aws.crossplane.io/v1beta1
              kind: Bucket
              spec:
                forProvider:
                  acl: private
                  versioningConfiguration:
                    status: Enabled
                  tagging:
                    tagSet: []
                  # ✅ AJOUTÉ: serverSideEncryptionConfiguration (requis par Kyverno)
                  serverSideEncryptionConfiguration:
                    rules:
                      - applyServerSideEncryptionByDefault:
                          sseAlgorithm: AES256
                  # ✅ AJOUTÉ: publicAccessBlockConfiguration (requis par Kyverno)
                  publicAccessBlockConfiguration:
                    blockPublicAcls: true
                    blockPublicPolicy: true
                    ignorePublicAcls: true
                    restrictPublicBuckets: true
                providerConfigRef:
                  name: default
                deletionPolicy: Delete
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.bucketName"
                toFieldPath: "metadata.name"
              
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.location"
                toFieldPath: "spec.forProvider.locationConstraint"
              
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.tags"
                toFieldPath: "spec.forProvider.tagging.tagSet"
          
          # Ressource 2: La BucketPolicy SSL (v1alpha3)
          - name: bucketpolicy-ssl
            base:
              apiVersion: s3.aws.crossplane.io/v1alpha3
              kind: BucketPolicy
              spec:
                forProvider:
                  bucketNameSelector:
                    matchControllerRef: true
                  policy:
                    version: "2012-10-17"
                    statements:
                      - sid: DenyInsecureTransport
                        effect: Deny
                        principal:
                          allowAnon: true
                        action:
                          - "s3:*"
                        resource: []  # sera patché
                        condition:
                          - operatorKey: Bool
                            conditions:
                              - key: "aws:SecureTransport"
                                stringValue: "false"  # ✅ CORRIGÉ: stringValue au lieu de boolValue
                providerConfigRef:
                  name: default
                deletionPolicy: Delete
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.bucketName"
                toFieldPath: "metadata.name"
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-ssl-policy"
              
              # Patch le ARN du bucket dans resource[0]
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.bucketName"
                toFieldPath: "spec.forProvider.policy.statements[0].resource[0]"
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "arn:aws:s3:::%s"
              
              # Patch le ARN du bucket dans resource[1]
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.bucketName"
                toFieldPath: "spec.forProvider.policy.statements[0].resource[1]"
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "arn:aws:s3:::%s/*"