apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3bucket-default
spec:
  compositeTypeRef:
    apiVersion: s3.aws.engie.org/v1alpha1
    kind: XBucket
  mode: Pipeline
  pipeline:
    - step: s3bucket
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: v1
        kind: PatchSet
        resources:
          - name: s3bucket
            base:
              apiVersion: s3.aws.crossplane.io/v1beta1
              kind: Bucket
              spec:
                providerConfigRef:
                  name: default
                deletionPolicy: Delete
                forProvider:
                  acl: private
                  versioningConfiguration:
                    status: Enabled

                  # ✅ Secure-by-default: Block Public Access
                  publicAccessBlockConfiguration:
                    blockPublicAcls: true
                    blockPublicPolicy: true
                    ignorePublicAcls: true
                    restrictPublicBuckets: true

                  # ✅ Secure-by-default: SSE AES256 (SSE-S3)
                  serverSideEncryptionConfiguration:
                    - rules:
                        - applyServerSideEncryptionByDefault:
                            sseAlgorithm: AES256

                  tagging:
                    tagSet: []

            patches:
              - fromFieldPath: "spec.bucketName"
                toFieldPath: "metadata.name"

              - fromFieldPath: "spec.location"
                toFieldPath: "spec.forProvider.locationConstraint"

              - fromFieldPath: "spec.tags"
                toFieldPath: "spec.forProvider.tagging.tagSet"

              # # ✅ Bucket policy HTTPS-only + TLS >= 1.2
              # - type: CombineFromComposite
              #   toFieldPath: "spec.forProvider.policy"
              #   combine:
              #     variables:
              #       - fromFieldPath: "metadata.name"
              #       - fromFieldPath: "metadata.name"
              #     strategy: string
              #     string:
              #       fmt: |
              #         {
              #           "Version":"2012-10-17",
              #           "Statement":[
              #             {
              #               "Sid":"DenyNonSSLRequests",
              #               "Effect":"Deny",
              #               "Principal":"*",
              #               "Action":"s3:*",
              #               "Resource":[
              #                 "arn:aws:s3:::%s",
              #                 "arn:aws:s3:::%s/*"
              #               ],
              #               "Condition":{"Bool":{"aws:SecureTransport":"false"}}
              #             },
              #             {
              #               "Sid":"DenyOldTLSVersions",
              #               "Effect":"Deny",
              #               "Principal":"*",
              #               "Action":"s3:*",
              #               "Resource":[
              #                 "arn:aws:s3:::%s",
              #                 "arn:aws:s3:::%s/*"
              #               ],
              #               "Condition":{"NumericLessThan":{"s3:TlsVersion":"1.2"}}
              #             }
              #           ]
              #         }
