apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v3.1.4
- namespace.yaml
- ingress.yaml

## changes to config maps
patches:
- path: argocd-cm-patch.yaml