apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/stable
    version: 1.15.0 # vérifie la dernière stable
    releaseName: crossplane
    namespace: crossplane-system
    valuesFile: values.yaml
