apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-s3-tags
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: check-s3-tags
      match:
        any:
          - resources:
              kinds:
                - Bucket
              apiGroups:
                - s3.aws.crossplane.io
      validate:
        message: "All S3 Buckets must have at least one tag defined."
        Pattern:
          spec:
            forProvider:
              tagging:
                tagSet:
                  - key: "?*"
                    value: "?*"
        deny:
          conditions:
            all:
              - key: "{{ request.object.spec.forProvider.tagging.tagSet | length(@) }}"
                operator: Equals
                value: 0