apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-s3-ssl
spec:
  validationFailureAction: enforce
  rules:
    - name: validate-ssl-policy-content
      match:
        any:
          - resources:
              apiGroups: ["s3.aws.crossplane.io"]
              kinds: ["BucketPolicy"]
      validate:
        message: "SSL must be enforced"
        pattern:
          spec:
            forProvider:
              policy: "*SecureTransport*"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-s3-encryption-in-transit
spec:
  validationFailureAction: enforce
  rules:
    - name: require-sse
      match:
        any:
          - resources:
              apiGroups: ["s3.aws.crossplane.io"]
              kinds: ["Bucket"]
      validate:
        message: "SSE is required"
        pattern:
          spec:
            forProvider:
              serverSideEncryptionConfiguration:
                - rules:
                    - applyServerSideEncryptionByDefault:
                        sseAlgorithm: "?*"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-s3-claim-ssl
spec:
  validationFailureAction: audit  # Important ✅
  rules:
    - name: require-ssl-in-claims
      match:
        any:
          - resources:
              apiGroups: ["s3.aws.engie.org"]
              kinds: ["BucketClaim"]
      validate:
        message: "Claims should prefer requireSSL=true"
        pattern:
          spec:
            =(requireSSL): true