apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-s3-tags
  annotations:
    policies.kyverno.io/title: Require S3 Bucket Tags
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Bucket
    policies.kyverno.io/description: >-
      Ensures that S3 buckets have required tags for cost allocation,
      ownership tracking, and resource management.
spec:
  validationFailureAction: enforce  # ✅ Enforce mode (blocks creation)
  background: true
  rules:
    - name: check-s3-tags
      match:
        any:
          - resources:
              kinds:
                - Bucket
              apiGroups:
                - s3.aws.crossplane.io
      # ✅ This policy applies ONLY to Buckets created by Crossplane
      # Direct creation attempts are already blocked by block-direct-bucket-creation
      validate:
        message: |
          ⚠️  TAGS MISSING: The bucket must have tags.
          
          Recommended tags:
          - Environment (dev, staging, production)
          - Owner (team name)
          - CostCenter
          - ApplicationId
          
          Required action: Add tags to your BucketClaim:
            spec:
              tags:
                - key: Environment
                  value: production
                - key: Owner
                  value: platform-team
                - key: CostCenter
                  value: CC-12345
                - key: ApplicationId
                  value: app-67890
          
          Documentation: https://wiki.engie.com/s3-tagging-policy
          Support: #platform-engineering
        pattern:
          spec:
            forProvider:
              tagging:
                tagSet:
                  - key: "*"
                    value: "*"