apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-s3-tags
spec:
  validationFailureAction: enforce  # ✅ Mode audit (ne bloque pas, juste log)
  background: true
  rules:
    - name: check-s3-tags
      match:
        any:
          - resources:
              kinds:
                - Bucket
              apiGroups:
                - s3.aws.crossplane.io
      # ✅ Cette policy s'applique SEULEMENT aux Buckets créés par Crossplane
      # Les tentatives de création directe sont déjà bloquées par block-direct-bucket-creation
      validate:
        message: |
          ⚠️  TAGS MANQUANTS : Le bucket devrait avoir des tags.
          
          Tags recommandés :
          - Environment (dev, staging, production)
          - Owner (nom de l'équipe)
          - CostCenter
        pattern:
          spec:
            forProvider:
              tagging:
                tagSet:
                  - key: "*"
                    value: "*"