apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Composition
      name: s3bucket-default
    patch: |-
      # 1) Remplacer tagSet (la clé existe déjà en base)
      - op: replace
        path: /spec/pipeline/0/input/resources/0/base/spec/forProvider/tagging/tagSet
        value:
          - key: Environment
            value: poc
          - key: Owner
            value: fac
          - key: Project
            value: demo

      # 2) Ajouter un patch qui définit la bucket policy (STRING JSON) avec 4 %s
      - op: add
        path: /spec/pipeline/0/input/resources/0/patches/-
        value:
          type: CombineFromComposite
          toFieldPath: spec.forProvider.policy
          combine:
            variables:
              - fromFieldPath: metadata.name
              - fromFieldPath: metadata.name
              - fromFieldPath: metadata.name
              - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: |
                {
                  "Version":"2012-10-17",
                  "Statement":[
                    {
                      "Sid":"DenyNonSSLRequests",
                      "Effect":"Deny",
                      "Principal":"*",
                      "Action":"s3:*",
                      "Resource":[
                        "arn:aws:s3:::%s",
                        "arn:aws:s3:::%s/*"
                      ],
                      "Condition":{"Bool":{"aws:SecureTransport":"false"}}
                    },
                    {
                      "Sid":"DenyOldTLSVersions",
                      "Effect":"Deny",
                      "Principal":"*",
                      "Action":"s3:*",
                      "Resource":[
                        "arn:aws:s3:::%s",
                        "arn:aws:s3:::%s/*"
                      ],
                      "Condition":{"NumericLessThan":{"s3:TlsVersion":"1.2"}}
                    }
                  ]
                }
