apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Composition
      name: s3bucket-default
    patch: |-
      # Remplacer le tagSet (clé déjà présente en base)
      - op: replace
        path: /spec/pipeline/0/input/resources/0/base/spec/forProvider/tagging/tagSet
        value:
          - key: Environment
            value: poc
          - key: Owner
            value: fac
          - key: Project
            value: demo

      # Patch 1
      - op: add
        path: /spec/pipeline/0/input/resources/0/patches/-
        value:
          type: CombineFromComposite
          toFieldPath: spec.forProvider.policy.Statement[0].Resource[0]
          combine:
            variables:
              - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: arn:aws:s3:::%s

      # Patch 2
      - op: add
        path: /spec/pipeline/0/input/resources/0/patches/-
        value:
          type: CombineFromComposite
          toFieldPath: spec.forProvider.policy.Statement[0].Resource[1]
          combine:
            variables:
              - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: arn:aws:s3:::%s/*

      # Patch 3
      - op: add
        path: /spec/pipeline/0/input/resources/0/patches/-
        value:
          type: CombineFromComposite
          toFieldPath: spec.forProvider.policy.Statement[1].Resource[0]
          combine:
            variables:
              - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: arn:aws:s3:::%s

      # Patch 4
      - op: add
        path: /spec/pipeline/0/input/resources/0/patches/-
        value:
          type: CombineFromComposite
          toFieldPath: spec.forProvider.policy.Statement[1].Resource[1]
          combine:
            variables:
              - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: arn:aws:s3:::%s/*