apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: composition-s3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Haliltarik/argocd-crossplane-kyverno.git
    targetRevision: main
    path: apps/crossplane/compositions/overlays/poc
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true