apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.5.1  # Utilisez la dernière version stable
    helm:
      releaseName: kyverno
      values: |
        replicaCount: 1
        installCRDs: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # - PrunePropagationPolicy=foreground
      # - PruneLast=true