apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-install
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kyverno/kyverno
    targetRevision: v1.15.1
    path: release/download   # ou la location précise dans le repo s'il ne s'agit pas d'un Helm chart
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
