apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Composition
      name: s3bucket-default
    patch: |-
      - op: add
        path: /spec/pipeline/0/input/resources/0/base/spec/forProvider/tagging/tagSet
        value:
          - key: Environment
            value: prod
          - key: Owner
            value: fac
          - key: Project
            value: demo
