apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: InjectedIdentity
  # assumeRole:
  #   roleARN: arn:aws:iam::407083967603:role/CrossplanePodIdentityRoleDev